@Restaurants.API_HostAddress = https://localhost:7067

GET {{Restaurants.API_HostAddress}}/api/restaurants

###


GET https://localhost:7067/api/Restaurants/5

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Bites",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "International Cuisine",
  "HasDelivery": true,
  "ContactEmail": "info@tastybites.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-001"
}

###

