@Restaurants.API_HostAddress = https://localhost:7067
@token = CfDJ8Pk5uW0cGtlCvC5EtxqUxHkPIHfuP7jeBNpLVoGBslq2r1AkI6oL3mL1dMB4CJN0dOOSy8Be0l1MuxmPBKCVrSeyZnh4CSzwtq7Bc_Gzblhyd7HGHJQeN72pw10Jb6ydwGUA_T-gI85XYGXXaWr_Ma9nx3yTzGiI1jik9XsGqXGXyFz_rBzSQJuHzpRiOqHXAQ3N-BgCyDJy3pVni035FLsjiax-DYtfscIUEhPkacbdKL_XjMKkss2j2buLSfYLj82NBg0k5Nw4B8B82aZ8wVOgqVJ8RNpdTXvDPgcs6P4abe0hmyLmEs4TWa1zh7iyovyK59wDQub_7a-U1Oak9fxT9JC3BoeKXceix7Pt5eNB7kkg0MunlcXVaKoP_aX_X_T-CqlCPaeuk1PK7hgG6OF2I0i1fVdUG805JIQX0V64-P4juyg3kPMU9VQqclXCOUguyaGyBkmzLYUJKNv99y8zshFQjJAqPfJeRnMIS3WpLfWxlbvJvizMnYO3dAKukIc6ihUj46SzWoEJp3YIvJ_oZOmsHoaUsmMtRHbTYvGtSKp2LTnOce8U7EgMxWxesqe1ss243tytdYb70BMY_Gg6E34lUudhTgzRdY2U8CYNvl4paHAjFrthPIUfXBL_InnBghwEPDzqz9tHyWfnuVwy5fsEv12Q9GI4KscyiXA3pJl9nOOE1RfUOdOTStJqEW7mvwM71ACVdUA-mAi66fHXwt2TRUJsCb2XjjQwvCtnkSCZguI9DfD2NnrbrLkR2xd-tWbrgKfBRC45aI_tPxTz2zH_dsVG5jjuV

GET {{Restaurants.API_HostAddress}}/api/restaurants

###


GET https://localhost:7067/api/Restaurants/5
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Tasty Bites 2",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tastybites.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-001"
}

###


@id=6
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=5
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

@restaurantId=0
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/6

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}
###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}