@Restaurants.API_HostAddress = https://localhost:7067
@token = CfDJ8Pk5uW0cGtlCvC5EtxqUxHmyf_ll-5sBIzUNtjGrk8D3zxNTU7xYNyVwhNcF3zEi7opCxk1trWL_V6OHEfgbZRQRod6ObL7B1qtDVh5Foo2ZB1mbhFb2jIkfUgIkDfo_fxIXabiwYLi1RFTq-IXhMoa1DIobAiUazOWwW4hk133A69av0otDP_DB9RKD6pWAT4bpIQg9wchKCEBZ9Sdfwy2AJMmC7UPhtMDlI6LxsPzXYjaktF_iRlEuFxnsMa-juobykr5Dz9-iZrFf_EUY5dlQwCjBAf-UsrMsjuFxXjMb4tR7fVumkEazWk_JPwgvdNZ6aWHv2BGj-apKTETmsUXnAw8mbtgkPbxPQOJua5gz-9d66puRGeKFIxCPR_cpDwfcksMjwQ659DzgL9wdAcd0ZJCkSyfi9WqlfSX86gBhFBHFn72xJdM6xso49sdROuW4LilJ7GivNifexohZbCD-eDYgIwMe4Tl5ESJTDY6kmJNaXaijupn02qcvyMLPiZT-HaTowAh7UAkzaWgoKcbFmEeoKYPVpE6bEcpb78rIO5peLbGLLCSA3o0IDbPW-rBsj631UkHE5qekA_OrSXhglgqcShj-cqSSRmHFmWwbkIiLaqNHuYeNm_gbUflgNi9ow8wAgLkIxE0DEt94CdxwwHeKYoIT51DPUWj1mAub5rXzf8j2sKFDvzRaRbDTCc5KWUaJhW4L0t0Ba-p5q3vPdhuKvL1gnFo-1yuwM1dW1yba2SBRXx3vDZa1o9g4nmEoS3Mtfh50lCb288LO-YUnERJbhPSDlEzbu9VMmkzV

GET {{Restaurants.API_HostAddress}}/api/restaurants

###


GET https://localhost:7067/api/Restaurants/5
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Owner Restaurant",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tastybites.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-001"
}

###


@id=6
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=5
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

@restaurantId=0
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/6

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}
###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}